[package]
name = "bevy_actify"
version = "0.2.0"
edition = "2024"
license = "MIT"
authors = ["iizudev"]

[features]
default = ["derive"]
derive = ["dep:bevy_actify_derive"]

[dependencies]
bevy = { version = "0.15", default-features = false }
bevy_actify_derive = { version = "0.2.0", optional = true }
