[package]
name = "bevy_actify"
version = { workspace = true }
edition = { workspace = true }

[features]
derive = []

[dependencies]
bevy = { version = "0.15", default-features = false }
bevy_actify_macros = { path = "../bevy_actify_derive" }
