name: Cargo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: "never"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - name: test (dev)
        run: cargo test --lib --all-features
      - name: test (release)
        run: cargo test --lib --all-features --release
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: rustfmt
        run: cargo fmt --check
      - name: clippy
        run: cargo clippy --no-deps
      - name: rustdoc
        run: cargo doc --no-deps
