name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --lib --verbose
      - name: Publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
